default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: rails_yelp_mvp_development

test:
  <<: *default
  database: rails_yelp_mvp_test

production:
  <<: *default
  database: rails_yelp_mvp_production
  username: rails_yelp_mvp
  password: <%= ENV["RAILS_YELP_MVP_DATABASE_PASSWORD"] %>
